services:
  oauth:
    build: .
    volumes:
      - ./certs:/app/certs
    ports:
      - "0.0.0.0:8080:8080"
    container_name: oauth-provider
    environment:
      - ADDRESS=0.0.0.0:8080
      - ISSUER_URL=http://oauth.local:8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=oauth_db
      - DB_SSLMODE=disable
      - COOKIE_SECRET=very-secret-string
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      internal:
      auth-common:
        aliases:
          - oauth.local

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oauth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      # cf. https://hub.docker.com/_/postgres#initialization-scripts
      - ./deployments/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:
    driver: bridge
  auth-common:
    external: true
    name: auth-common-net

volumes:
  pgdata: